name: Backend Continuous Deployment

on:
  workflow_dispatch:

  push:
    branches: main

defaults:
  run:
    working-directory: starter/backend

env:
  PYTHON_VERSION: '3.10.6'
  CLUSTER_NAME: cluster

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code from Rep
      uses: actions/checkout@v3



    - name: Set up environment
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Restore Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.local/share/virtualenvs
          ~/.pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Dependencies
      run:  |
        python -m pip install --upgrade pip
        pip install pipenv
        pip install flake8

    - name: Run the Linter
      run: pipenv run lint

    - name: Install pytest
      run: pipenv install pytest

    - name: Test
      run: pipenv run test