name: Backend Continuous Integration

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    path:
      - '../../starter/backend/**'

defaults:
  run:
    working-directory: ./starter/backend

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Check the Repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Restore Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Dependencies
      run:  pip install pipenv

    - name: Run the Linter
      run: pipenv run lint

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check the Repository
      uses: actions/checkout@v3

    - name: Use Python 3
      uses:  actions/setup-python@v5
      with:
        python-version: "3.10"
    
    - name: Install pipenv
      run: pip install pipenv

    - name: Install Dependencies
      run:  pip install

    - name: Test
      run: pipenv run test
